import { Box, Grid } from '@mui/material';
import React from 'react';
import { ProductCard } from '../../components';

const Products = () => {
    return (
        <Box>
            <Grid container/*  spacing={2} */>
                {groceryItems.map((item) => (
                    <Grid key={item.productCode} item xs={12} sm={6} md={4}>
                        <ProductCard product={item} />
                    </Grid>
                ))}
            </Grid>
        </Box>
    );
};

export default Products;

const groceryItems = [
    {
      productName: 'Apple',
      price: 2.99,
      discountPercentage: 10,
      status: 'In stock',
      productDescription: 'Fresh and juicy apples.',
      type: 'Fruits',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-15',
      category: 'Produce',
      countInStock: 50,
      productPicture: 'https://example.com/apple.jpg',
      brand: 'Fresh Farms',
      productCode: 'APL001',
      reviewPoint: 4.5,
      productPlan: 'Organic',
      weight: '1 kg',
    },
    {
      productName: 'Banana',
      price: 1.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Ripe and delicious bananas.',
      type: 'Fruits',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-10',
      category: 'Produce',
      countInStock: 70,
      productPicture: 'https://example.com/banana.jpg',
      brand: 'Tropical Delight',
      productCode: 'BAN001',
      reviewPoint: 4.7,
      productPlan: 'Recommended',
      weight: '500 gm',
    },
    {
      productName: 'Orange',
      price: 3.29,
      discountPercentage: 5,
      status: 'In stock',
      productDescription: 'Sweet and tangy oranges.',
      type: 'Fruits',
      manufacturingDate: '2023-08-02',
      expireDate: '2023-08-18',
      category: 'Produce',
      countInStock: 30,
      productPicture: 'https://example.com/orange.jpg',
      brand: 'Citrus Farms',
      productCode: 'ORG001',
      reviewPoint: 4.3,
      productPlan: '',
      weight: '750 gm',
    },
    {
      productName: 'Carrot',
      price: 1.25,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and crunchy carrots.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-08-16',
      category: 'Produce',
      countInStock: 60,
      productPicture: 'https://example.com/carrot.jpg',
      brand: 'Green Fields',
      productCode: 'CRT001',
      reviewPoint: 4.1,
      productPlan: 'Recommended',
      weight: '500 gm',
    },
    {
      productName: 'Potato',
      price: 1.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and versatile potatoes.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-04',
      expireDate: '2023-08-20',
      category: 'Produce',
      countInStock: 40,
      productPicture: 'https://example.com/potato.jpg',
      brand: 'Farmers Choice',
      productCode: 'POT001',
      reviewPoint: 4.2,
      productPlan: '',
      weight: '1 kg',
    },
    {
      productName: 'Spinach',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Nutritious and fresh spinach leaves.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-05',
      expireDate: '2023-08-22',
      category: 'Produce',
      countInStock: 25,
      productPicture: 'https://example.com/spinach.jpg',
      brand: 'Organic Greens',
      productCode: 'SPN001',
      reviewPoint: 4.8,
      productPlan: 'Organic',
      weight: '500 gm',
    },
    {
      productName: 'Chicken Eggs (Dozen)',
      price: 3.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Farm-fresh eggs from free-range chickens.',
      type: 'Dairy & Eggs',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-14',
      category: 'Eggs',
      countInStock: 100,
      productPicture: 'https://example.com/eggs.jpg',
      brand: 'Happy Hen',
      productCode: 'EGG001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '12 eggs',
    },
    {
      productName: 'Whole Milk (1L)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Creamy and rich whole milk.',
      type: 'Dairy & Eggs',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-10',
      category: 'Milk',
      countInStock: 60,
      productPicture: 'https://example.com/milk.jpg',
      brand: 'Fresh Meadows',
      productCode: 'MLK001',
      reviewPoint: 4.4,
      productPlan: 'Recommended',
      weight: '1L',
    },
    {
      productName: 'Yogurt (500g)',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Creamy and delicious yogurt.',
      type: 'Dairy & Eggs',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-10',
      category: 'Dairy',
      countInStock: 50,
      productPicture: 'https://example.com/yogurt.jpg',
      brand: 'Dairy Delights',
      productCode: 'YGT001',
      reviewPoint: 4.3,
      productPlan: 'Recommended',
      weight: '500 gm',
    },
    {
      productName: 'Brown Bread',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Healthy and whole grain brown bread.',
      type: 'Bakery',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-08',
      category: 'Bread',
      countInStock: 40,
      productPicture: 'https://example.com/bread.jpg',
      brand: 'Nature\'s Harvest',
      productCode: 'BRD001',
      reviewPoint: 4.5,
      productPlan: 'Recommended',
      weight: '400 gm',
    },
    {
      productName: 'Chicken (1 kg)',
      price: 7.99,
      discountPercentage: 15,
      status: 'In stock',
      productDescription: 'Fresh and tender chicken meat.',
      type: 'Meat & Poultry',
      manufacturingDate: '2023-08-02',
      expireDate: '2023-08-17',
      category: 'Meat',
      countInStock: 20,
      productPicture: 'https://example.com/chicken.jpg',
      brand: 'Farmers Market',
      productCode: 'CHN001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '1 kg',
    },
    {
      productName: 'Salmon (200g)',
      price: 9.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and premium salmon fillet.',
      type: 'Seafood',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-08-13',
      category: 'Fish',
      countInStock: 15,
      productPicture: 'https://example.com/salmon.jpg',
      brand: 'Ocean Catch',
      productCode: 'SLM001',
      reviewPoint: 4.8,
      productPlan: '',
      weight: '200 gm',
    },
    {
      productName: 'Rice (5 kg)',
      price: 12.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'High-quality long-grain rice.',
      type: 'Grains & Rice',
      manufacturingDate: '2023-08-05',
      expireDate: '2023-09-30',
      category: 'Rice',
      countInStock: 30,
      productPicture: 'https://example.com/rice.jpg',
      brand: 'Golden Grains',
      productCode: 'RC001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '5 kg',
    },
    {
      productName: 'Pasta',
      price: 1.79,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Premium-quality pasta for delicious meals.',
      type: 'Pasta & Noodles',
      manufacturingDate: '2023-08-06',
      expireDate: '2024-02-28',
      category: 'Pasta',
      countInStock: 25,
      productPicture: 'https://example.com/pasta.jpg',
      brand: 'Italian Delight',
      productCode: 'PST001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Olive Oil (500ml)',
      price: 4.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Imported and flavorful extra virgin olive oil.',
      type: 'Cooking Oil & Ghee',
      manufacturingDate: '2023-07-31',
      expireDate: '2024-07-31',
      category: 'Oil',
      countInStock: 30,
      productPicture: 'https://example.com/olive-oil.jpg',
      brand: 'Mediterranean Gold',
      productCode: 'OIL001',
      reviewPoint: 4.6,
      productPlan: 'Recommended',
      weight: '500 ml',
    },
    {
      productName: 'Salt (500g)',
      price: 0.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Pure and iodized table salt.',
      type: 'Spices & Seasonings',
      manufacturingDate: '2023-08-01',
      expireDate: '2024-08-01',
      category: 'Salt',
      countInStock: 40,
      productPicture: 'https://example.com/salt.jpg',
      brand: 'Crystal Clear',
      productCode: 'SLT001',
      reviewPoint: 4.2,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Sugar (1 kg)',
      price: 1.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Premium-quality granulated sugar.',
      type: 'Spices & Seasonings',
      manufacturingDate: '2023-08-01',
      expireDate: '2024-08-01',
      category: 'Sugar',
      countInStock: 50,
      productPicture: 'https://example.com/sugar.jpg',
      brand: 'Sweet Choice',
      productCode: 'SGR001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '1 kg',
    },
    {
      productName: 'Coffee (250g)',
      price: 5.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Premium coffee beans for rich flavor.',
      type: 'Beverages',
      manufacturingDate: '2023-07-30',
      expireDate: '2024-07-30',
      category: 'Coffee',
      countInStock: 35,
      productPicture: 'https://example.com/coffee.jpg',
      brand: 'Gourmet Brews',
      productCode: 'COF001',
      reviewPoint: 4.7,
      productPlan: 'Recommended',
      weight: '250 gm',
    },
    {
      productName: 'Tea Bags (100)',
      price: 3.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'High-quality tea bags for a delightful brew.',
      type: 'Beverages',
      manufacturingDate: '2023-07-31',
      expireDate: '2024-07-31',
      category: 'Tea',
      countInStock: 40,
      productPicture: 'https://example.com/tea.jpg',
      brand: 'Tea Haven',
      productCode: 'TEA001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '100 tea bags',
    },
    {
      productName: 'Cereal',
      price: 3.29,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Crunchy and nutritious breakfast cereal.',
      type: 'Breakfast',
      manufacturingDate: '2023-08-01',
      expireDate: '2024-01-31',
      category: 'Cereal',
      countInStock: 30,
      productPicture: 'https://example.com/cereal.jpg',
      brand: 'Morning Delight',
      productCode: 'CRL001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Applesauce',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Smooth and natural applesauce.',
      type: 'Breakfast',
      manufacturingDate: '2023-08-02',
      expireDate: '2024-02-29',
      category: 'Sauce',
      countInStock: 20,
      productPicture: 'https://example.com/applesauce.jpg',
      brand: 'Pure Naturals',
      productCode: 'APP001',
      reviewPoint: 4.2,
      productPlan: '',
      weight: '400 gm',
    },
    {
      productName: 'Orange Juice (1L)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Refreshing and natural orange juice.',
      type: 'Beverages',
      manufacturingDate: '2023-08-02',
      expireDate: '2024-02-29',
      category: 'Juice',
      countInStock: 30,
      productPicture: 'https://example.com/orange-juice.jpg',
      brand: 'Sunshine Sips',
      productCode: 'OJU001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '1L',
    },
    {
      productName: 'Cookies',
      price: 1.79,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Delicious and crunchy cookies.',
      type: 'Snacks',
      manufacturingDate: '2023-08-01',
      expireDate: '2024-02-29',
      category: 'Cookies',
      countInStock: 40,
      productPicture: 'https://example.com/cookies.jpg',
      brand: 'Sweet Treats',
      productCode: 'CKS001',
      reviewPoint: 4.3,
      productPlan: '',
      weight: '250 gm',
    },
    {
      productName: 'Chips',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Crispy and flavorful potato chips.',
      type: 'Snacks',
      manufacturingDate: '2023-08-02',
      expireDate: '2024-02-29',
      category: 'Chips',
      countInStock: 30,
      productPicture: 'https://example.com/chips.jpg',
      brand: 'Crunchy Bites',
      productCode: 'CHP001',
      reviewPoint: 4.5,
      productPlan: 'Recommended',
      weight: '150 gm',
    },
    {
      productName: 'Chocolate Bar',
      price: 0.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Indulgent and smooth chocolate bar.',
      type: 'Snacks',
      manufacturingDate: '2023-08-01',
      expireDate: '2024-02-29',
      category: 'Chocolates',
      countInStock: 50,
      productPicture: 'https://example.com/chocolate.jpg',
      brand: 'Divine Delights',
      productCode: 'CHC001',
      reviewPoint: 4.7,
      productPlan: '',
      weight: '50 gm',
    },
    {
      productName: 'Cheese (200g)',
      price: 3.79,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Premium-quality cheese for savory dishes.',
      type: 'Dairy & Eggs',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-12-31',
      category: 'Cheese',
      countInStock: 25,
      productPicture: 'https://example.com/cheese.jpg',
      brand: 'Cheese Lover\'s',
      productCode: 'CHS001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '200 gm',
    },
    {
      productName: 'Ice Cream',
      price: 4.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Creamy and indulgent ice cream.',
      type: 'Frozen Foods',
      manufacturingDate: '2023-08-04',
      expireDate: '2024-08-04',
      category: 'Ice Cream',
      countInStock: 20,
      productPicture: 'https://example.com/ice-cream.jpg',
      brand: 'Frozen Delights',
      productCode: 'ICR001',
      reviewPoint: 4.8,
      productPlan: 'Recommended',
      weight: '500 ml',
    },
    {
      productName: 'Frozen Pizza',
      price: 6.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Delicious frozen pizza for quick meals.',
      type: 'Frozen Foods',
      manufacturingDate: '2023-08-05',
      expireDate: '2024-08-05',
      category: 'Pizza',
      countInStock: 15,
      productPicture: 'https://example.com/frozen-pizza.jpg',
      brand: 'Pizza Perfect',
      productCode: 'PZZ001',
      reviewPoint: 4.4,
      productPlan: 'Recommended',
      weight: '400 gm',
    },
    {
      productName: 'Instant Noodles',
      price: 0.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Quick and tasty instant noodles.',
      type: 'Pasta & Noodles',
      manufacturingDate: '2023-08-06',
      expireDate: '2024-08-06',
      category: 'Noodles',
      countInStock: 50,
      productPicture: 'https://example.com/instant-noodles.jpg',
      brand: 'Quick Noms',
      productCode: 'NDL001',
      reviewPoint: 4.2,
      productPlan: '',
      weight: '70 gm',
    },
    {
      productName: 'Canned Tomato Sauce',
      price: 1.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Rich and tangy canned tomato sauce.',
      type: 'Canned & Jarred',
      manufacturingDate: '2023-08-01',
      expireDate: '2024-08-01',
      category: 'Sauce',
      countInStock: 40,
      productPicture: 'https://example.com/tomato-sauce.jpg',
      brand: 'Saucy Tomatoes',
      productCode: 'TMS001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '400 gm',
    },
    {
      productName: 'Peanut Butter (500g)',
      price: 3.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Creamy and delicious peanut butter.',
      type: 'Canned & Jarred',
      manufacturingDate: '2023-08-02',
      expireDate: '2024-08-02',
      category: 'Butter & Spreads',
      countInStock: 30,
      productPicture: 'https://example.com/peanut-butter.jpg',
      brand: 'Nutty Delights',
      productCode: 'PBR001',
      reviewPoint: 4.6,
      productPlan: 'Recommended',
      weight: '500 gm',
    },
    {
      productName: 'Canned Tuna (150g)',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'High-quality canned tuna in brine.',
      type: 'Canned & Jarred',
      manufacturingDate: '2023-08-03',
      expireDate: '2025-08-03',
      category: 'Tuna',
      countInStock: 25,
      productPicture: 'https://example.com/tuna.jpg',
      brand: 'Ocean Breeze',
      productCode: 'TUN001',
      reviewPoint: 4.7,
      productPlan: '',
      weight: '150 gm',
    },
    {
      productName: 'Instant Coffee (100g)',
      price: 5.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Premium instant coffee for quick brewing.',
      type: 'Beverages',
      manufacturingDate: '2023-08-04',
      expireDate: '2024-08-04',
      category: 'Coffee',
      countInStock: 20,
      productPicture: 'https://example.com/instant-coffee.jpg',
      brand: 'Quick Brew',
      productCode: 'ICO001',
      reviewPoint: 4.4,
      productPlan: 'Recommended',
      weight: '100 gm',
    },
    {
      productName: 'Tea Leaves (250g)',
      price: 4.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Premium loose tea leaves for brewing.',
      type: 'Beverages',
      manufacturingDate: '2023-08-05',
      expireDate: '2024-08-05',
      category: 'Tea',
      countInStock: 35,
      productPicture: 'https://example.com/tea-leaves.jpg',
      brand: 'Aromatic Teas',
      productCode: 'TLV001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '250 gm',
    },
    {
      productName: 'Granola Bars',
      price: 2.79,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Healthy and tasty granola bars.',
      type: 'Snacks',
      manufacturingDate: '2023-08-06',
      expireDate: '2024-02-28',
      category: 'Bars',
      countInStock: 30,
      productPicture: 'https://example.com/granola-bars.jpg',
      brand: 'Nutritious Bites',
      productCode: 'GBR001',
      reviewPoint: 4.3,
      productPlan: '',
      weight: '200 gm',
    },
    {
      productName: 'Honey (500g)',
      price: 6.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Pure and natural honey.',
      type: 'Baking',
      manufacturingDate: '2023-08-01',
      expireDate: '2025-08-01',
      category: 'Honey',
      countInStock: 40,
      productPicture: 'https://example.com/honey.jpg',
      brand: 'Golden Nectar',
      productCode: 'HNY001',
      reviewPoint: 4.6,
      productPlan: 'Recommended',
      weight: '500 gm',
    },
    {
      productName: 'Flour (2 kg)',
      price: 3.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'High-quality all-purpose flour.',
      type: 'Baking',
      manufacturingDate: '2023-08-02',
      expireDate: '2024-08-02',
      category: 'Flour',
      countInStock: 30,
      productPicture: 'https://example.com/flour.jpg',
      brand: 'Pure Flours',
      productCode: 'FLR001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '2 kg',
    },
    {
      productName: 'Baking Soda (500g)',
      price: 1.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Pure and high-quality baking soda.',
      type: 'Baking',
      manufacturingDate: '2023-08-03',
      expireDate: '2024-08-03',
      category: 'Baking Soda',
      countInStock: 25,
      productPicture: 'https://example.com/baking-soda.jpg',
      brand: 'Baker\'s Secret',
      productCode: 'BSD001',
      reviewPoint: 4.2,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Cooking Oil (1L)',
      price: 4.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Healthy and versatile cooking oil.',
      type: 'Cooking Oil & Ghee',
      manufacturingDate: '2023-08-04',
      expireDate: '2024-08-04',
      category: 'Oil',
      countInStock: 20,
      productPicture: 'https://example.com/cooking-oil.jpg',
      brand: 'Cook\'s Choice',
      productCode: 'OIL002',
      reviewPoint: 4.8,
      productPlan: 'Recommended',
      weight: '1L',
    },
    {
      productName: 'Butter (250g)',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Creamy and delicious butter.',
      type: 'Cooking Oil & Ghee',
      manufacturingDate: '2023-08-05',
      expireDate: '2024-08-05',
      category: 'Butter & Spreads',
      countInStock: 25,
      productPicture: 'https://example.com/butter.jpg',
      brand: 'Dairy Delights',
      productCode: 'BTR001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '250 gm',
    },
    {
      productName: 'Hamburger Buns',
      price: 1.79,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and soft hamburger buns.',
      type: 'Bakery',
      manufacturingDate: '2023-08-06',
      expireDate: '2023-08-10',
      category: 'Bread',
      countInStock: 40,
      productPicture: 'https://example.com/hamburger-buns.jpg',
      brand: 'Bakery Bliss',
      productCode: 'HMB001',
      reviewPoint: 4.3,
      productPlan: '',
      weight: '400 gm',
    },
    {
      productName: 'Ground Beef (500g)',
      price: 5.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and premium ground beef.',
      type: 'Meat & Poultry',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-14',
      category: 'Meat',
      countInStock: 20,
      productPicture: 'https://example.com/ground-beef.jpg',
      brand: 'Prime Cuts',
      productCode: 'GBF001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Chicken Nuggets',
      price: 4.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Delicious and crispy chicken nuggets.',
      type: 'Frozen Foods',
      manufacturingDate: '2023-08-02',
      expireDate: '2024-02-28',
      category: 'Chicken',
      countInStock: 25,
      productPicture: 'https://example.com/chicken-nuggets.jpg',
      brand: 'Nugget Delights',
      productCode: 'NUG001',
      reviewPoint: 4.8,
      productPlan: '',
      weight: '400 gm',
    },
    {
      productName: 'Frozen Peas (500g)',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and tender frozen peas.',
      type: 'Frozen Foods',
      manufacturingDate: '2023-08-03',
      expireDate: '2024-08-03',
      category: 'Vegetables',
      countInStock: 30,
      productPicture: 'https://example.com/frozen-peas.jpg',
      brand: 'Green Harvest',
      productCode: 'FPE001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Frozen Corn (500g)',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and flavorful frozen corn.',
      type: 'Frozen Foods',
      manufacturingDate: '2023-08-04',
      expireDate: '2024-08-04',
      category: 'Vegetables',
      countInStock: 25,
      productPicture: 'https://example.com/frozen-corn.jpg',
      brand: 'Gold Kernels',
      productCode: 'FCN001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Frozen Mixed Vegetables (1kg)',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'A mix of assorted frozen vegetables.',
      type: 'Frozen Foods',
      manufacturingDate: '2023-08-05',
      expireDate: '2024-08-05',
      category: 'Vegetables',
      countInStock: 20,
      productPicture: 'https://example.com/frozen-vegetables.jpg',
      brand: 'Fresh Picks',
      productCode: 'FMV001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '1 kg',
    },
    {
      productName: 'Fresh Salmon Fillet (500g)',
      price: 10.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and premium salmon fillet.',
      type: 'Seafood',
      manufacturingDate: '2023-08-06',
      expireDate: '2023-08-20',
      category: 'Fish',
      countInStock: 15,
      productPicture: 'https://example.com/salmon-fillet.jpg',
      brand: 'Ocean Catch',
      productCode: 'FSM001',
      reviewPoint: 4.8,
      productPlan: 'Recommended',
      weight: '500 gm',
    },
    {
      productName: 'Fresh Shrimp (500g)',
      price: 9.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and succulent shrimp.',
      type: 'Seafood',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-15',
      category: 'Shrimp',
      countInStock: 20,
      productPicture: 'https://example.com/shrimp.jpg',
      brand: 'Sea Breeze',
      productCode: 'SHR001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Salmon Sushi Roll',
      price: 6.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Delicious and fresh salmon sushi roll.',
      type: 'Ready-to-Eat',
      manufacturingDate: '2023-08-02',
      expireDate: '2023-08-08',
      category: 'Sushi',
      countInStock: 25,
      productPicture: 'https://example.com/sushi-roll.jpg',
      brand: 'Sushi Master',
      productCode: 'SUS001',
      reviewPoint: 4.7,
      productPlan: '',
      weight: '250 gm',
    },
    {
      productName: 'Cheese Pizza',
      price: 7.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Delicious cheese pizza with tomato sauce.',
      type: 'Ready-to-Eat',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-08-09',
      category: 'Pizza',
      countInStock: 30,
      productPicture: 'https://example.com/cheese-pizza.jpg',
      brand: 'Pizza Paradise',
      productCode: 'PCZ001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '400 gm',
    },
    {
      productName: 'Chocolate Chip Cookies',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Freshly baked chocolate chip cookies.',
      type: 'Ready-to-Eat',
      manufacturingDate: '2023-08-04',
      expireDate: '2023-08-10',
      category: 'Cookies',
      countInStock: 40,
      productPicture: 'https://example.com/chocolate-chip-cookies.jpg',
      brand: 'Sweet Delights',
      productCode: 'CCC001',
      reviewPoint: 4.3,
      productPlan: '',
      weight: '200 gm',
    },
    {
      productName: 'Blueberry Muffins',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Freshly baked blueberry muffins.',
      type: 'Ready-to-Eat',
      manufacturingDate: '2023-08-05',
      expireDate: '2023-08-11',
      category: 'Muffins',
      countInStock: 35,
      productPicture: 'https://example.com/blueberry-muffins.jpg',
      brand: 'Muffin Mania',
      productCode: 'MUF001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '250 gm',
    },
    {
      productName: 'Freshly Squeezed Orange Juice (500ml)',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Freshly squeezed orange juice.',
      type: 'Beverages',
      manufacturingDate: '2023-08-06',
      expireDate: '2023-08-20',
      category: 'Juice',
      countInStock: 30,
      productPicture: 'https://example.com/fresh-orange-juice.jpg',
      brand: 'Citrus Sips',
      productCode: 'OJU002',
      reviewPoint: 4.6,
      productPlan: 'Recommended',
      weight: '500 ml',
    },
    {
      productName: 'Lemonade (1L)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Refreshing and zesty lemonade.',
      type: 'Beverages',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-10',
      category: 'Lemonade',
      countInStock: 40,
      productPicture: 'https://example.com/lemonade.jpg',
      brand: 'Lemon Bliss',
      productCode: 'LEM001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '1L',
    },
    {
      productName: 'Vanilla Ice Cream (500ml)',
      price: 4.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Classic and creamy vanilla ice cream.',
      type: 'Frozen Foods',
      manufacturingDate: '2023-08-02',
      expireDate: '2023-08-15',
      category: 'Ice Cream',
      countInStock: 25,
      productPicture: 'https://example.com/vanilla-ice-cream.jpg',
      brand: 'Creamy Dreams',
      productCode: 'ICR002',
      reviewPoint: 4.7,
      productPlan: 'Recommended',
      weight: '500 ml',
    },
    {
      productName: 'Chocolate Ice Cream (500ml)',
      price: 4.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Rich and indulgent chocolate ice cream.',
      type: 'Frozen Foods',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-08-16',
      category: 'Ice Cream',
      countInStock: 20,
      productPicture: 'https://example.com/chocolate-ice-cream.jpg',
      brand: 'Chocoholic Delight',
      productCode: 'ICR003',
      reviewPoint: 4.8,
      productPlan: '',
      weight: '500 ml',
    },
    {
      productName: 'Fresh Strawberries (500g)',
      price: 3.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and juicy fresh strawberries.',
      type: 'Fruits',
      manufacturingDate: '2023-08-04',
      expireDate: '2023-08-10',
      category: 'Berries',
      countInStock: 15,
      productPicture: 'https://example.com/strawberries.jpg',
      brand: 'Berry Garden',
      productCode: 'STW001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Fresh Blueberries (250g)',
      price: 4.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and plump fresh blueberries.',
      type: 'Fruits',
      manufacturingDate: '2023-08-05',
      expireDate: '2023-08-11',
      category: 'Berries',
      countInStock: 20,
      productPicture: 'https://example.com/blueberries.jpg',
      brand: 'Berry Blast',
      productCode: 'BLB001',
      reviewPoint: 4.5,
      productPlan: 'Recommended',
      weight: '250 gm',
    },
    {
      productName: 'Bananas (1 kg)',
      price: 1.79,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and nutritious bananas.',
      type: 'Fruits',
      manufacturingDate: '2023-08-06',
      expireDate: '2023-08-12',
      category: 'Bananas',
      countInStock: 30,
      productPicture: 'https://example.com/bananas.jpg',
      brand: 'Nature\'s Harvest',
      productCode: 'BNN001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '1 kg',
    },
    {
      productName: 'Green Apples (1 kg)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Crisp and tart green apples.',
      type: 'Fruits',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-08',
      category: 'Apples',
      countInStock: 40,
      productPicture: 'https://example.com/green-apples.jpg',
      brand: 'Fresh Orchard',
      productCode: 'APL001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '1 kg',
    },
    {
      productName: 'Red Apples (1 kg)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Juicy and sweet red apples.',
      type: 'Fruits',
      manufacturingDate: '2023-08-02',
      expireDate: '2023-08-09',
      category: 'Apples',
      countInStock: 35,
      productPicture: 'https://example.com/red-apples.jpg',
      brand: 'Fresh Orchard',
      productCode: 'APL002',
      reviewPoint: 4.5,
      productPlan: 'Recommended',
      weight: '1 kg',
    },
    {
      productName: 'Green Grapes (500g)',
      price: 3.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and seedless green grapes.',
      type: 'Fruits',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-08-09',
      category: 'Grapes',
      countInStock: 25,
      productPicture: 'https://example.com/green-grapes.jpg',
      brand: 'Grapevine Delights',
      productCode: 'GRP001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Red Grapes (500g)',
      price: 3.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and seedless red grapes.',
      type: 'Fruits',
      manufacturingDate: '2023-08-04',
      expireDate: '2023-08-10',
      category: 'Grapes',
      countInStock: 20,
      productPicture: 'https://example.com/red-grapes.jpg',
      brand: 'Grapevine Delights',
      productCode: 'GRP002',
      reviewPoint: 4.7,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Avocado',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Ripe and creamy avocado.',
      type: 'Fruits',
      manufacturingDate: '2023-08-05',
      expireDate: '2023-08-10',
      category: 'Avocado',
      countInStock: 30,
      productPicture: 'https://example.com/avocado.jpg',
      brand: 'Healthy Greens',
      productCode: 'AVC001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '1 piece',
    },
    {
      productName: 'Pineapple',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and juicy pineapple.',
      type: 'Fruits',
      manufacturingDate: '2023-08-06',
      expireDate: '2023-08-12',
      category: 'Pineapple',
      countInStock: 25,
      productPicture: 'https://example.com/pineapple.jpg',
      brand: 'Tropical Treats',
      productCode: 'PNP001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '1 piece',
    },
    {
      productName: 'Watermelon',
      price: 3.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Juicy and refreshing watermelon.',
      type: 'Fruits',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-06',
      category: 'Watermelon',
      countInStock: 20,
      productPicture: 'https://example.com/watermelon.jpg',
      brand: 'Summer Fresh',
      productCode: 'WMN001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '1 piece',
    },
    {
      productName: 'Carrots (500g)',
      price: 1.29,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and crunchy carrots.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-02',
      expireDate: '2023-08-08',
      category: 'Carrots',
      countInStock: 40,
      productPicture: 'https://example.com/carrots.jpg',
      brand: 'Fresh Greens',
      productCode: 'CRT001',
      reviewPoint: 4.3,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Broccoli (500g)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and nutritious broccoli.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-08-09',
      category: 'Broccoli',
      countInStock: 35,
      productPicture: 'https://example.com/broccoli.jpg',
      brand: 'Fresh Greens',
      productCode: 'BRC001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Cucumbers (500g)',
      price: 1.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and crisp cucumbers.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-04',
      expireDate: '2023-08-10',
      category: 'Cucumbers',
      countInStock: 30,
      productPicture: 'https://example.com/cucumbers.jpg',
      brand: 'Fresh Greens',
      productCode: 'CUC001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Bell Peppers (500g)',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Colorful and crunchy bell peppers.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-05',
      expireDate: '2023-08-11',
      category: 'Bell Peppers',
      countInStock: 25,
      productPicture: 'https://example.com/bell-peppers.jpg',
      brand: 'Fresh Greens',
      productCode: 'BPP001',
      reviewPoint: 4.4,
      productPlan: 'Recommended',
      weight: '500 gm',
    },
    {
      productName: 'Spinach (500g)',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and nutritious spinach.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-06',
      expireDate: '2023-08-12',
      category: 'Spinach',
      countInStock: 30,
      productPicture: 'https://example.com/spinach.jpg',
      brand: 'Fresh Greens',
      productCode: 'SPN001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Tomatoes (500g)',
      price: 1.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and juicy tomatoes.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-06',
      category: 'Tomatoes',
      countInStock: 35,
      productPicture: 'https://example.com/tomatoes.jpg',
      brand: 'Fresh Greens',
      productCode: 'TMT001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Onions (1 kg)',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and pungent onions.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-02',
      expireDate: '2023-08-08',
      category: 'Onions',
      countInStock: 40,
      productPicture: 'https://example.com/onions.jpg',
      brand: 'Fresh Greens',
      productCode: 'ONN001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '1 kg',
    },
    {
      productName: 'Potatoes (1 kg)',
      price: 1.79,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and versatile potatoes.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-08-09',
      category: 'Potatoes',
      countInStock: 30,
      productPicture: 'https://example.com/potatoes.jpg',
      brand: 'Fresh Greens',
      productCode: 'POT001',
      reviewPoint: 4.3,
      productPlan: '',
      weight: '1 kg',
    },
    {
      productName: 'Sweet Potatoes (1 kg)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and nutritious sweet potatoes.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-04',
      expireDate: '2023-08-10',
      category: 'Sweet Potatoes',
      countInStock: 25,
      productPicture: 'https://example.com/sweet-potatoes.jpg',
      brand: 'Fresh Greens',
      productCode: 'SPT001',
      reviewPoint: 4.5,
      productPlan: 'Recommended',
      weight: '1 kg',
    },
    {
      productName: 'Mushrooms (500g)',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and earthy mushrooms.',
      type: 'Vegetables',
      manufacturingDate: '2023-08-05',
      expireDate: '2023-08-11',
      category: 'Mushrooms',
      countInStock: 20,
      productPicture: 'https://example.com/mushrooms.jpg',
      brand: 'Fresh Greens',
      productCode: 'MSH001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Eggs (Dozen)',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and organic eggs.',
      type: 'Dairy & Eggs',
      manufacturingDate: '2023-08-06',
      expireDate: '2023-08-12',
      category: 'Eggs',
      countInStock: 30,
      productPicture: 'https://example.com/eggs.jpg',
      brand: 'Eggcellent',
      productCode: 'EGG001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '1 dozen',
    },
    {
      productName: 'Milk (1L)',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Fresh and nutritious cow\'s milk.',
      type: 'Dairy & Eggs',
      manufacturingDate: '2023-08-01',
      expireDate: '2023-08-08',
      category: 'Milk',
      countInStock: 35,
      productPicture: 'https://example.com/milk.jpg',
      brand: 'Dairy Delights',
      productCode: 'MLK001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '1L',
    },
    {
      productName: 'Greek Yogurt (500g)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Thick and creamy Greek yogurt.',
      type: 'Dairy & Eggs',
      manufacturingDate: '2023-08-02',
      expireDate: '2023-08-08',
      category: 'Yogurt',
      countInStock: 40,
      productPicture: 'https://example.com/greek-yogurt.jpg',
      brand: 'Yogurt Plus',
      productCode: 'YGT001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '500 gm',
    },
    {
      productName: 'Cheddar Cheese (250g)',
      price: 3.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sharp and delicious cheddar cheese.',
      type: 'Dairy & Eggs',
      manufacturingDate: '2023-08-03',
      expireDate: '2023-08-09',
      category: 'Cheese',
      countInStock: 25,
      productPicture: 'https://example.com/cheddar-cheese.jpg',
      brand: 'Cheese Kingdom',
      productCode: 'CHS001',
      reviewPoint: 4.7,
      productPlan: 'Recommended',
      weight: '250 gm',
    },
    {
      productName: 'Butter Croissants (Pack of 4)',
      price: 3.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Flaky and buttery croissants.',
      type: 'Bakery',
      manufacturingDate: '2023-08-04',
      expireDate: '2023-08-08',
      category: 'Croissants',
      countInStock: 20,
      productPicture: 'https://example.com/croissants.jpg',
      brand: 'Bakery Bliss',
      productCode: 'CRS001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '4 pieces',
    },
    {
      productName: 'Whole Wheat Bread',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Healthy and wholesome whole wheat bread.',
      type: 'Bakery',
      manufacturingDate: '2023-08-05',
      expireDate: '2023-08-09',
      category: 'Bread',
      countInStock: 35,
      productPicture: 'https://example.com/whole-wheat-bread.jpg',
      brand: 'Bakery Bliss',
      productCode: 'BRD001',
      reviewPoint: 4.5,
      productPlan: 'Recommended',
      weight: '400 gm',
    },
    {
      productName: 'Bagels (Pack of 6)',
      price: 3.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Soft and chewy bagels.',
      type: 'Bakery',
      manufacturingDate: '2023-08-06',
      expireDate: '2023-08-10',
      category: 'Bagels',
      countInStock: 30,
      productPicture: 'https://example.com/bagels.jpg',
      brand: 'Bakery Bliss',
      productCode: 'BGL001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '6 pieces',
    },
    {
      productName: 'Multigrain Crackers',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Nutritious and crunchy multigrain crackers.',
      type: 'Snacks',
      manufacturingDate: '2023-08-01',
      expireDate: '2024-02-01',
      category: 'Crackers',
      countInStock: 40,
      productPicture: 'https://example.com/multigrain-crackers.jpg',
      brand: 'Snack Masters',
      productCode: 'MGC001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '300 gm',
    },
    {
      productName: 'Potato Chips',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Crispy and savory potato chips.',
      type: 'Snacks',
      manufacturingDate: '2023-08-02',
      expireDate: '2024-02-02',
      category: 'Chips',
      countInStock: 45,
      productPicture: 'https://example.com/potato-chips.jpg',
      brand: 'Snack Masters',
      productCode: 'PCH001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '150 gm',
    },
    {
      productName: 'Assorted Nuts (500g)',
      price: 5.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'A mix of assorted nuts.',
      type: 'Snacks',
      manufacturingDate: '2023-08-03',
      expireDate: '2024-02-03',
      category: 'Nuts',
      countInStock: 30,
      productPicture: 'https://example.com/assorted-nuts.jpg',
      brand: 'Nuts Galore',
      productCode: 'NUT001',
      reviewPoint: 4.6,
      productPlan: 'Recommended',
      weight: '500 gm',
    },
    {
      productName: 'Dark Chocolate Bar',
      price: 3.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Rich and indulgent dark chocolate bar.',
      type: 'Snacks',
      manufacturingDate: '2023-08-04',
      expireDate: '2024-02-04',
      category: 'Chocolate',
      countInStock: 25,
      productPicture: 'https://example.com/dark-chocolate-bar.jpg',
      brand: 'Chocoholic Delight',
      productCode: 'CHC001',
      reviewPoint: 4.7,
      productPlan: '',
      weight: '100 gm',
    },
    {
      productName: 'Gummy Bears',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Sweet and chewy gummy bears.',
      type: 'Snacks',
      manufacturingDate: '2023-08-05',
      expireDate: '2024-02-05',
      category: 'Candy',
      countInStock: 30,
      productPicture: 'https://example.com/gummy-bears.jpg',
      brand: 'Candy Kingdom',
      productCode: 'GMY001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '150 gm',
    },
    {
      productName: 'Sparkling Water (500ml)',
      price: 0.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Refreshing and bubbly sparkling water.',
      type: 'Beverages',
      manufacturingDate: '2023-08-06',
      expireDate: '2024-02-06',
      category: 'Water',
      countInStock: 35,
      productPicture: 'https://example.com/sparkling-water.jpg',
      brand: 'Bubbles',
      productCode: 'SPW001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '500 ml',
    },
    {
      productName: 'Iced Tea (500ml)',
      price: 1.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Refreshing and sweet iced tea.',
      type: 'Beverages',
      manufacturingDate: '2023-08-01',
      expireDate: '2024-02-01',
      category: 'Tea',
      countInStock: 40,
      productPicture: 'https://example.com/iced-tea.jpg',
      brand: 'Tea Time',
      productCode: 'TEA001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '500 ml',
    },
    {
      productName: 'Instant Coffee (200g)',
      price: 5.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Rich and aromatic instant coffee.',
      type: 'Beverages',
      manufacturingDate: '2023-08-02',
      expireDate: '2024-02-02',
      category: 'Coffee',
      countInStock: 25,
      productPicture: 'https://example.com/instant-coffee.jpg',
      brand: 'Coffee Haven',
      productCode: 'CFF001',
      reviewPoint: 4.7,
      productPlan: '',
      weight: '200 gm',
    },
    {
      productName: 'Earl Grey Tea',
      price: 2.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Classic and aromatic Earl Grey tea.',
      type: 'Beverages',
      manufacturingDate: '2023-08-03',
      expireDate: '2024-02-03',
      category: 'Tea',
      countInStock: 20,
      productPicture: 'https://example.com/earl-grey-tea.jpg',
      brand: 'Tea Time',
      productCode: 'TEA002',
      reviewPoint: 4.6,
      productPlan: 'Recommended',
      weight: '100 gm',
    },
    {
      productName: 'Energy Drink (250ml)',
      price: 2.49,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Boost your energy with this energy drink.',
      type: 'Beverages',
      manufacturingDate: '2023-08-04',
      expireDate: '2024-02-04',
      category: 'Energy Drink',
      countInStock: 20,
      productPicture: 'https://example.com/energy-drink.jpg',
      brand: 'Energize',
      productCode: 'EGD001',
      reviewPoint: 4.6,
      productPlan: '',
      weight: '250 ml',
    },
    {
      productName: 'Sports Drink (500ml)',
      price: 1.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Stay hydrated with this sports drink.',
      type: 'Beverages',
      manufacturingDate: '2023-08-05',
      expireDate: '2024-02-05',
      category: 'Sports Drink',
      countInStock: 25,
      productPicture: 'https://example.com/sports-drink.jpg',
      brand: 'Energize',
      productCode: 'SGD001',
      reviewPoint: 4.5,
      productPlan: '',
      weight: '500 ml',
    },
    {
      productName: 'Lemon Lime Soda (500ml)',
      price: 0.99,
      discountPercentage: 0,
      status: 'In stock',
      productDescription: 'Refreshing and bubbly lemon-lime soda.',
      type: 'Beverages',
      manufacturingDate: '2023-08-06',
      expireDate: '2024-02-06',
      category: 'Soda',
      countInStock: 30,
      productPicture: 'https://example.com/lemon-lime-soda.jpg',
      brand: 'Soda Fizz',
      productCode: 'LSD001',
      reviewPoint: 4.4,
      productPlan: '',
      weight: '500 ml',
    },
  ];
  
  